pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('_____________________________Build_____________________________') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('_____________________________Test_____________________________') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('_____________________________Deliver_____________________________') {
            steps {
                sh 'chmod 777 ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('____________________________Build____________________________') {
            steps {

                 app = docker.build("voodooq3/maven")

            }
        }
    }
}