pipeline {
  environment {
    registry = "voodooq3/docker-test"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  
    agent {
        docker {
            image 'maven:3.6.3-jdk-8'
//            image 'maven:latest'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    stages {
        stage('***************** GIT *****************') {
            steps {
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        
        stage('***************** Build *****************') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('***************** Test *****************') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('***************** Deliver *****************') {
            steps { 
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
// ================================
stage('***************** Building image *****************') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('***************** Deploy Image *****************') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('***************** Remove Unused docker image *****************') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }    
 
    
// ================================
    }
}